## Numpy

It is known as numerical python.

It is a python library that deals with the arrays.

It is the fundamental package for scientific computing.

Numpy are faster than lists.

#### Arrays in numpy

The array object in numpy is called as ndarray.

The arrays are: 0-d array, 1-d array, 2-d array, 3-d array.

In [1]:
import numpy as np

In [2]:
ar=np.array(2)
print(ar)

2


In [3]:
l= [1,2,3,4,5]
arr= np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]

arr1=np.array([l1,l2])

In [7]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr1.shape

(2, 5)

#### Indexing in arrays

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0.

In [9]:
a1= np.array([56,78,11,20,99,44])
print(a1)

[56 78 11 20 99 44]


In [10]:
print(a1[0])

56


In [11]:
print(a1[3:])

[20 99 44]


Negative indexing can be used to access elements of the array.

In [12]:
print(a1[-1])

44


In [13]:
print(a1[:-1])

[56 78 11 20 99]


In [14]:
a2=np.array([[6,7,1,2,5],[5,9,2,1,4]])
print(a2)

[[6 7 1 2 5]
 [5 9 2 1 4]]


In [15]:
print(a2[1][:-1])  #[represents the row(0 or 1)][required values]

[5 9 2 1]


In [16]:
print(a2[:3,:-1])    #[row1][row2]

[[6 7 1 2]
 [5 9 2 1]]


#### Various functions of numpy array

np.ones(): Create array of 1s

In [17]:
np.ones(3)

array([1., 1., 1.])

np.zeros(): Create array of 0s

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

np.random.random(): Create array of random numbers

In [19]:
np.random.random(20)

array([0.94374242, 0.88503114, 0.35346346, 0.67694495, 0.71934261,
       0.51819678, 0.87144417, 0.93206456, 0.15674439, 0.78553654,
       0.42788922, 0.05291243, 0.40233978, 0.21989494, 0.33899619,
       0.38549286, 0.55256865, 0.48829623, 0.14210046, 0.44320763])

np.arange(): Create array with increments of a fixed step size

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

np.linspace(): Create array of fixed length

In [21]:
np.linspace(2,7,5)

array([2.  , 3.25, 4.5 , 5.75, 7.  ])

np.full(): Create a constant array of any number ‘n’

In [22]:
np.full(5,23)

array([23, 23, 23, 23, 23])

np.tile(): Create a new array by repeating an existing array for a particular number of times

In [23]:
np.tile([4,5,6],2)

array([4, 5, 6, 4, 5, 6])

np.eye(): Create an identity matrix of any dimension

In [24]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.randint(): Create a random array of integers within a particular range

In [25]:
np.random.randint(5,20,5)

array([ 9, 13, 10, 10,  6])

#### ndim in numpy

For checking the number of dimensions in numpy array, <ndim> attribute is used.


In [26]:
a2.ndim

2

#### Shape and reshape of array

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [28]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


The shape of an array is the number of elements in each dimension.

The shape is checked using <array.shape>.

In [29]:
arr.shape

(12,)

Reshaping means changing the size of an array.

The reshaping is done by using <array.reshape()>.

In [30]:
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Pandas

Pandas is a library which is used to work with the datasets.

It deals with cleaning, exploring, manipulating and analyzing the data.

It can clean messy and noisy datasets.

It analyzes big data and make conclusion based on statistical theories.


In [31]:
import pandas as pd

In [32]:
print(pd.__version__)

1.3.4


Data frames are usually multi-dimensional tables.

Data frame is a 2-d data structure, a table with row and columns.

In [33]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=["Col1","Col2","Col3","Col4"])

In [34]:
df.head()

Col1  Col2  Col3  Col4
R1     0     1     2     3
R2     4     5     6     7
R3     8     9    10    11
R4    12    13    14    15
R5    16    17    18    19

In [35]:
df.tail(2)

Col1  Col2  Col3  Col4
R4    12    13    14    15
R5    16    17    18    19

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, R1 to R5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [37]:
df.describe()

Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [38]:
df.shape

(5, 4)

#### Accessing elements from dataframe

The loc() function is label based data selecting method which means that we have to pass the name of the row or column which we want to select.

In [39]:
df.loc['R2']

Col1    4
Col2    5
Col3    6
Col4    7
Name: R2, dtype: int32

The iloc() function is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column. 

In [40]:
df.iloc[:,:]

Col1  Col2  Col3  Col4
R1     0     1     2     3
R2     4     5     6     7
R3     8     9    10    11
R4    12    13    14    15
R5    16    17    18    19

In [41]:
df.iloc[:2,:4]

Col1  Col2  Col3  Col4
R1     0     1     2     3
R2     4     5     6     7

In [42]:
df.iloc[:,:-1]

Col1  Col2  Col3
R1     0     1     2
R2     4     5     6
R3     8     9    10
R4    12    13    14
R5    16    17    18

In [43]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [44]:
df['Col2'].value_counts()

1     1
5     1
9     1
13    1
17    1
Name: Col2, dtype: int64